In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [2]:
x_train =np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35],[1543,4,1,32]])
y_train = np.array([460000, 232000, 178000,340000])
print(f'training data : {x_train}')
print(f'actual price of data : {y_train}')

training data : [[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]
 [1543    4    1   32]]
actual price of data : [460000 232000 178000 340000]


In [35]:
#  prediction of a model
# initialized parameter
w  = [1200,3200,2030,1010]
b = 150
def prediction(x_data,w,b):
    n = x_data.shape[0]
    pred = np.zeros(n)
    
    for i in range(n):
        dat = np.sum(np.dot(x_data[i],w)) +b
        pred[i]=dat
    return pred
#  cost of model 
def cost_model(x_data,y_data):
    cost = 0
    m = x_data.shape[0]
    n = 2*m
    for i in range(x_data.shape[0]):
        cos =( x_data[i]-y_data[i])**2
        cost = cost + cos
    cost = cost/n
    return cost
def gradient(x_data,y_data,data):
    m = len(x_data)
    bi =0
    wi =np.zeros(m)
    for i in range(m):
        diff = x_data[i]-y_data[i]
        for j in range(m):
            wi[j] = wi[j]+ diff * data[i][j]
            bi = bi + diff
    wi = wi/m
    bi = bi/m
    return wi,bi
def gradient_descent(x_data,y_data,lr,itr):
    m = x_data.shape[0]
    hist = []
    w ,b = 10000,18900
    cost = []
    for i in range(itr):
        predict = prediction(x_data,w,b)
        wit,bis = gradient(predict,y_data,x_data)
        w = w - (lr*wit)
        b = b - (lr * bis)
        if i % 100000 ==0:
            cost.append(cost_model(predict,y_data))
            hist.append([w,b])
            print(f"weight : {w}  bais : {b } " )
    return w,b,hist,cost,predict
            
            

        
        

In [ ]:
weight,bais,w_b,cost,pred =gradient_descent(x_train,y_train,0.000000001,1000000) 

weight : [9975.96741862 9999.94296685 9999.98146937 9999.4182418 ]  bais : 18899.9402744 
weight : [ -69.75235973 9977.90903562 9986.35290914 9661.57804986]  bais : 18863.867296159002 
weight : [ -67.46668425 9979.71814263 9980.48266289 9567.29391595]  bais : 18852.805073268573 
weight : [ -65.19837919 9981.51719853 9974.6475804  9473.7262089 ]  bais : 18841.828492591278 
weight : [ -62.94731264 9983.30627958 9968.84739482 9380.86948838]  bais : 18830.936903756065 
weight : [ -60.7133537  9985.08546145 9963.08184132 9288.71835539]  bais : 18820.129661331284 
weight : [ -58.49637246 9986.85481925 9957.35065709 9197.26745192]  bais : 18809.40612478575 
weight : [ -56.29624    9988.61442752 9951.6535813  9106.51146065]  bais : 18798.76565845267 


In [ ]:
pred

In [30]:
cost

[121107008355000.0,
 6507332213.534591,
 6498182863.793821,
 6489047449.155709,
 6479925948.391968,
 6470818340.306666,
 6461724603.736069,
 6452644717.548865,
 6443578660.645809,
 6434526411.9597435]

In [ ]:
weight